/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ESCOLA
 */
public class JFLogin extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public JFLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4Usuario = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1Senha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jTextField2Usuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("autenticação");
        setBackground(new java.awt.Color(255, 51, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4Usuario.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4Usuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Rubik", 0, 12)); // NOI18N
        jButton1.setText("Entrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4Usuario.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 80, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Rubik", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("senha:");
        jPanel4Usuario.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 50, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-cadeado-24.png"))); // NOI18N
        jPanel4Usuario.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 70, 40));

        jPasswordField1Senha.setText("1234");
        jPasswordField1Senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1SenhaActionPerformed(evt);
            }
        });
        jPanel4Usuario.add(jPasswordField1Senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 200, -1));

        jLabel1.setFont(new java.awt.Font("Rubik", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("usuario:");
        jPanel4Usuario.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 60, 30));

        jTextField2Usuario.setText("emerson");
        jTextField2Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2UsuarioActionPerformed(evt);
            }
        });
        jPanel4Usuario.add(jTextField2Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 200, 20));

        getContentPane().add(jPanel4Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 310));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/login_newpng.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 160, 240));

        jLabel4.setText("Secretário de Emerson");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField1SenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1SenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1SenhaActionPerformed

    private void jTextField2UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2UsuarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String usuario = jTextField2Usuario.getText();
        String senha = jPasswordField1Senha.getText();
        if(usuario.equals("emerson") && senha.equals("1234")){ 
           Main main = new Main();
           main.setExtendedState(JFrame.MAXIMIZED_BOTH);
           main.setVisible(true);
           dispose();
        } else{ 
           JOptionPane.showMessageDialog(null,"Login ou senha invalidos") ;
    }//GEN-LAST:event_jButton1ActionPerformed
    }    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel4Usuario;
    private javax.swing.JPasswordField jPasswordField1Senha;
    private javax.swing.JTextField jTextField2Usuario;
    // End of variables declaration//GEN-END:variables
}
